[workspace]
members = ["doplarr", "radarr_api", "sonarr_api"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[workspace.metadata.crane]
name = "doplarr"
